stages:
  base_future:
    cmd: python scripts/run_base_future.py
    deps:
      - Interface_RDM.xlsx
      - src/workflow/0_Scenarios/
      - src/workflow/1_Experiment/0_From_Confection/B1_Model_Structure.xlsx
      - scripts/run_base_future.py
    params:
      - Interface_RDM.xlsx:
          Setup:
            - Run_Base_Future
            - Solver
            - OSeMOSYS_Model_Name
            - Region
    outs:
      - src/workflow/1_Experiment/Executables/:
          cache: true
          persist: false
    metrics:
      - src/workflow/1_Experiment/Executables/metrics.json:
          cache: false
    desc: Execute base future scenario (Future 0) with selected solver

  rdm_experiment:
    cmd: python scripts/run_rdm_experiment.py
    deps:
      - Interface_RDM.xlsx
      - src/workflow/1_Experiment/0_From_Confection/B1_Model_Structure.xlsx
      - src/workflow/0_Scenarios/
      - src/workflow/2_Miscellaneous/shape_of_demand.csv
      - scripts/run_rdm_experiment.py
    params:
      - Interface_RDM.xlsx:
          Setup:
            - Run_RDM
            - Solver
            - OSeMOSYS_Model_Name
            - Region
            - Timeslices_model
          Uncertainty_Table
    outs:
      - src/workflow/1_Experiment/Experimental_Platform/:
          cache: true
          persist: false
    metrics:
      - src/workflow/1_Experiment/Experimental_Platform/rdm_metrics.json:
          cache: false
    desc: Execute RDM experiment with Latin Hypercube Sampling uncertainty analysis

  postprocess:
    cmd: python scripts/run_postprocess.py
    deps:
      - src/workflow/1_Experiment/Experimental_Platform/
      - src/workflow/3_Postprocessing/config_concatenate.yaml
      - src/workflow/3_Postprocessing/create_csv_concatenate.py
      - scripts/run_postprocess.py
    outs:
      - src/Results/:
          cache: true
    metrics:
      - src/Results/postprocess_metrics.json:
          cache: false
    desc: Aggregate and concatenate results from all RDM futures into final CSVs

  prim_analysis:
    cmd: python scripts/run_prim.py
    deps:
      - src/Results/
      - src/workflow/4_PRIM/PRIM_config.xlsx
      - src/workflow/4_PRIM/PRIM_new.py
      - scripts/run_prim.py
    outs:
      - src/workflow/4_PRIM/Output/:
          cache: true
    plots:
      - src/workflow/4_PRIM/Output/prim_plots.json:
          cache: false
    desc: Perform PRIM (Patient Rule Induction Method) scenario discovery analysis
